### PR TITLE
Add atraeger9-Lake Oswego file

### LINKED ISSUE #32: Create a new file for atraeger9 Lake Oswego, OR
- [x] Create a branch
- [x] Add Comments
- [x] Open a PR
- [ ] Have a Discussion
- [ ] Seek Approval
- [ ] Merge PR

### PR DESCRIPTION
**Pull request by atraeger9**
closes #32

### CODE REVIEW

**Review by dmukherj — COMMENTED** [review]
What pizza should I order?

**Comment by dmukherj** [comment]
🌵

**Comment by atraeger9** [comment]
@deb1895 You can create your own artisan pizza here

**Review by DataDredger — APPROVED** [review]
Looks good!

**Review by dmukherj — COMMENTED** [review]
looks good

**Pull request merged**
